# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyDictionaryApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyDictionaryApp
  rn_path = '../node_modules/react-native'
  pod 'React', path: rn_path, subspecs: [
  'Core',
  'RCTActionSheet',
  'RCTAnimation',
  'RCTGeolocation',
  'RCTImage',
  'RCTLinkingIOS',
  'RCTNetwork',
  'RCTSettings',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket',
  'ART',
  'CxxBridge',
  'DevSupport'
  ]
  
  # React Native third party dependencies podspecs
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  # If you are using React Native <0.54, you will get the following error:
  # "The name of the given podspec `GLog` doesn't match the expected one `glog`"
  # Use the following line instead:
  #pod 'GLog', :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
  
  pod 'RNSound', :path => '../node_modules/react-native-sound'

  post_install do |installer|
      installer.pods_project.targets.each do |target|
          if target.name == "react-native-google-maps"
              target.build_configurations.each do |config|
                  config.build_settings["CLANG_ENABLE_MODULES"] = "No"
              end
          end
          if target.name == "React"
              target.remove_from_project
          end
      end
  end    

end
